movie_ror/config/routes.rb
Rails.application.routes.draw do
  get 'message/show'
  get 'usergroup/create'
  get 'bookmovie/new'
  get 'bookmovie/create'
  get 'group/new'
  get 'group/create'
  get 'group/show'
  get 'usergroup/show'
  get 'usergroup/approve'
  get 'usergroup/reject'
  post 'usergroup/approve' =>'usergroup#approve'
  patch 'usergroup/approve' =>'usergroup#approve'
  post 'usergroup/reject' =>'usergroup#reject'
  patch 'usergroup/reject' =>'usergroup#reject'
  get 'movie/new'
  get 'movie/create'
  get 'movie/show'
  get 'movie/book'
  post 'movie/book'=>'movie#book'
  get 'user/show'
  get 'user/create'
  get 'main/login'=>'main#login'
  post 'main/login'=>'main#login'
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  delete 'session/destroy'
  post 'group/join'
  get 'group/join'
  get 'user/create_user'
  post 'user/create_user'
 # get 'user/save_user'
  post 'user/save_user'
   #get 'movie/three'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#login'

end

movie_ror/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

movie_ror/app/models/bookmovie.rb
class Bookmovie < ApplicationRecord
	#belongs_to :user
end

movie_ror/app/models/group.rb
class Group < ApplicationRecord
	#belongs_to :user
end

movie_ror/app/models/message.rb
class Message < ApplicationRecord
end

movie_ror/app/models/movie.rb
class Movie < ApplicationRecord
end

movie_ror/app/models/user.rb
class User < ApplicationRecord
	#attr_accessor :password_confirmation
	#validates :password_confirmation, :presence =>true
	#validates :password, :confirmation => true
	#validates_confirmation_of :password
	#validates_presence_of :password_confirmation
	#validates :password, confirmation: true
  	#attr_accessible :password_confirmation
  	#attr_accessor :password
end

movie_ror/app/models/usergroup.rb
class Usergroup < ApplicationRecord
end

movie_ror/app/controllers/bookmovie_controller.rb
class BookmovieController < ApplicationController
  def new
  end

  def create
  	@bookmovie = Bookmovie.new(bookmovie_params)
  end
end

movie_ror/app/controllers/group_controller.rb
class GroupController < ApplicationController
  def new
  end

  def create
  	@group = Group.new(group_params)
  end
  def show
    if session[:user] == nil
      redirect_to main_login_path
    end
  @user=User.find(params[:user][:id])
   names=@user.uname
  @group1=Group.where(Group.arel_table[:admin].does_not_match(names))
   if @group1.size == 0
      @group = Group.all
   else
      @group = @group1
    end
  end
  def join
  	@group = Group.find(params[:bid])
    @user = User.find(params[:user][:id])
    names=@user.uname
    gname=@group.id
    #@group1=Group.where(:id =>gname,:admin =>names)
    @usergroup1=Usergroup.where(:gname => gname , :uname =>names)

      if @usergroup1.size == 0
        @usergroup = Usergroup.new
        @usergroup.uname = @user.uname
        @usergroup.gname = @group.id
        @usergroup.status = 'P'
        if @usergroup.save
          flash[:success] = "Request sent to administrator"
          redirect_to action:"show",user:session[:user]
        end  
      else
        if @usergroup1[0].status == "P"
          flash[:failure] = "Your request is already pending with the administrator"
          redirect_to action:"show",user:session[:user]
        else
          if @usergroup1[0].status == 'R'
            @usergroup = Usergroup.new
            @usergroup.uname = @user.uname
            @usergroup.gname = @group.id
            @usergroup.status = 'P'
            if @usergroup.save
              flash[:success] = "Request sent to administrator"
              redirect_to action:"show",user:session[:user]
            end   
          else
             flash[:success] = "You are already a member of this group"
              redirect_to action:"show",user:session[:user]
          end  
        end
      end
    
   
  end
  
end

movie_ror/app/controllers/main_controller.rb
class MainController < ApplicationController

  	def login
  		if (request.method=="GET" )
  			@err=session[:uname]
			if(not session[:user].nil?)
				redirect_to main_login_path
			end
		#print form
			#setmessage()

		elsif (request.method=="POST")

			#session[:isadmin]=0
			@err=[]

			#user authenticate
			if(params[:uname].empty? or params[:password].empty?)
				@err.push("Fields can't be blank");
				flash[:notice_err] = "Fields can't be blank"
			end

			if(@err.size>0)
				session[:uname]=@err
				#flash[:notice] = "Fields can't be blank"
				flash[:notice_err] = "Fields can't be blank"
				redirect_to action:"login"
			else
			#check in db
				@us=User.where(:uname=>params[:uname])
				if( @us.size>0)
					@us=@us[0]
					if(@us.password==params[:password])
						session[:user]=@us
						redirect_to :controller =>"session",:action => "new",:user =>session[:user]
					else
						@err.push("Password Incorrect")
						flash[:notice_err] = "Password Incorrect"
						session[:uname]=@err
					 	redirect_to :action=>"login",:alert=> "Incorrect password"
					end	
				else
					@err.push("Invalid User. Please sign Up")
					flash[:notice_err] = "Invalid User. Please sign Up"
					session[:uname]=@err
					 redirect_to :action=>"login",:alert=> "Invalid User. Please sign Up"
				end
			end
		end
	end

end	

movie_ror/app/controllers/message_controller.rb
class MessageController < ApplicationController
  def show
    if session[:user] == nil
      redirect_to main_login_path
    end
  	@user = User.find(params[:uname][:id])
  	name = @user.uname
  	i = 0
  	gname=[]
  	@ugroup = Usergroup.where(:uname => name,:status => 'A')
  	@ugroup.each do |e|  
  		gname[i]=e.gname
  		i=i+1
  	end
  	#gname = @ugroup.find(@ugroup.gname)
  	@msg = Message.where(:gname =>gname)
  end
end

movie_ror/app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def new
  end

  def create
  	@movie = Movie.new(movie_params)
  end

  def show
  	if session[:user] == nil
      redirect_to main_login_path
    end
    @movie = Movie.all
  end

  def book
  	@mov = Movie.find(params[:bid])
    @user = User.find(params[:user][:id])
    uname = @user.uname
    mov = @mov.mname
    @bk = Bookmovie.where(:mname=> mov ,:uname => uname)
    if @bk.size == 0
      @bookmovie=Bookmovie.new
      @bookmovie.mname = @mov.mname
      @bookmovie.uname = @user.uname
      if @bookmovie.save
          list_group = Usergroup.where(:uname => params[:user][:uname],:status => 'A').uniq
          list_group.each { |x|  
          @message = Message.new
          @message.gname = x.gname
          @message.message = "The user "+ uname + " has booked for movie "+mov
          @message.save
        }
        redirect_to movie_show_path
      end
    else
      flash[:notice] = "You have already booked for this movie"
      redirect_to movie_show_path
    end
  end
end

movie_ror/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  	if session[:user] == nil
      redirect_to main_login_path
    end
    @user =User.find(params[:user])
    @uname = @user.name
  end

  def create
  end

  def destroy
  	#User.find(session[:user]).destroy
  	session[:user] = nil
  	redirect_to main_login_path
  end
end

movie_ror/app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  	
  end

  def create
  	@user = User.new(user_params)
  	
  end
  def create_user
  	#@user = User.new(user_params)
  end
  def save_user
  	@user = User.new
  	us_name = params[:uname]
  	@dup_user = User.where(:uname => us_name)
  	if @dup_user.size == 0
  		@user.uname = params[:uname]
  		@user.password = params[:password]
  		@user.name = params[:name]
  		if @user.save
  			flash[:notice] = "You can login to system now"
     	 	redirect_to main_login_path
     	 end
   	else
     	 	flash[:notice_err] = "Username already exist use your existing password to login"
     	 	redirect_to main_login_path
  	end
  end

  #private
 # def user_params
  #	params.require(:user).permit(:uname,:password,:name)
  #end
end

movie_ror/app/helpers/application_helper.rb
module ApplicationHelper
end

movie_ror/app/helpers/bookmovie_helper.rb
module BookmovieHelper
end

movie_ror/app/helpers/group_helper.rb
module GroupHelper
end

movie_ror/app/helpers/main_helper.rb
module MainHelper
end

movie_ror/app/helpers/message_helper.rb
module MessageHelper
end

movie_ror/app/helpers/movie_helper.rb
module MovieHelper
end

movie_ror/app/helpers/session_helper.rb
module SessionHelper
end

movie_ror/app/helpers/user_helper.rb
module UserHelper
end

movie_ror/app/helpers/usergroup_helper.rb
module UsergroupHelper
end

movie_ror/app/views/bookmovie/create.html.erb
<h1>Bookmovie#create</h1>
<p>Find me in app/views/bookmovie/create.html.erb</p>

movie_ror/app/views/bookmovie/new.html.erb
<h1>Bookmovie#new</h1>
<p>Find me in app/views/bookmovie/new.html.erb</p>

movie_ror/app/views/group/create.html.erb
<h1>Group#create</h1>
<p>Find me in app/views/group/create.html.erb</p>

movie_ror/app/views/group/new.html.erb
<h1>Group#new</h1>
<p>Find me in app/views/group/new.html.erb</p>

movie_ror/app/views/group/show.html.erb
<br/><h2 style="text-align:center">Groups Available</h2>
<% if flash[:success]  %>

<font color="green"><strong>
	<%= flash[:success]  %></strong>
</font>
<% end %>
<% if flash[:failure]  %>

<font color="red"><strong>
	<%= flash[:failure]  %></strong>
</font>
<% end %>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<div class="groups">
<center>
	<table class="table table-hover">
		<thead>
			<tr>
			<th>Group Name</th>
			<th>Admin</th>
		</tr>
		</thead>
		<tbody>
		<% @group.each do |x| %>
			<tr>
				<td><%= x.gname %></td>
				<td><%= x.admin %></td>
				<td>	
					<%= link_to "Join" ,controller:"group",action:"join",bid:x.id,user:session[:user] %></br>
				</td>
			</tr>
		</tbody>
		<% end %>
	</table>
	</center>
</div>

movie_ror/app/views/message/show.html.erb
<br/><h2 style="text-align:center">Messages</h2>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<div class="messages">
<center>
	<table class="table table-hover">
		<thead>
		<tr>
			<th>Group Name</th>
			<th>Message</th>
		</tr>
		</thead>
		<tbody>
		<% @msg.each do |x| %>
			<tr>
				<td><%= x.gname %></td>
				<td><%= x.message %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
	</center>
</div>

movie_ror/app/views/movie/create.html.erb
<h1>Movie#create</h1>
<p>Find me in app/views/movie/create.html.erb</p>

movie_ror/app/views/movie/new.html.erb
<h1>Movie has been booked</h1>
<p>Please click on the link to go to home page
<%= link_to "Home " , session_new_path %>
</p>

movie_ror/app/views/movie/show.html.erb
<br/><h2 style="text-align:center">Movies Available</h2>
<% if flash[:notice]  %>

<font color="red"><strong>
	<%= flash[:notice]  %></strong>
</font>
<% end %>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<div class="movies">
<center>
	<table class="table table-hover">
		<thead>
		<tr>
			<th>Banner</th>
			<th>Name</th>
			<th>Type</th>
			<th>Language</th>
		</tr>
		</thead>
		<tbody>
		<% @movie.each do |x| %>
			<tr>
				<td><img src="<%= x.picture %>" height="100" width="100"></img></td>
				<%#<img src="<%= x.picture %><%#{}" class="img-rounded" >%>
				<td><%= x.mname %></td>
				<td><%= x.mtype %></td>
				<td><%= x.lang %></td>
				<td>	
					<%= link_to "Book" ,action:"book",bid:x.id,user:session[:user] %></br>
				</td>
			</tr>
		<% end %>
		</tbody>

	</table>
	</center>
</div>

movie_ror/app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

movie_ror/app/views/user/create_user.html.erb
<center>
<h1>Sign Up Page</h1>
<%= form_tag(action:"save_user",method:"post") do %>
	<body>
		<center>
			<table>
				<tr>
					<td class="input" ><%= label_tag :uname,"User Name:" %></td>
					<td class="input"><%= text_field_tag(:uname) %></br></td>
				</tr>
				<%#</tr>%>
				<tr>
					<td class="input"><%= label_tag :name,"Name:" %></td>
					<td class="input"><%= text_field_tag(:name) %></td>
				</tr>
				</tr>
				<tr>
					<td class="input"><%= label_tag :password,"Password:" %></td>
					<td class="input"><%= password_field_tag(:password) %></td>
				</tr>
				</tr>
				<tr><td class="button"><%= submit_tag("            SignUp           ")%></td></tr>
			</br>
			</br>
			</br>
			</table>
		</center>
		</body>
	<% end %> 
</center>
<script type="text/javascript">
    function Validate() {
        var password = document.getElementById("txtPassword").value;
        var confirmPassword = document.getElementById("txtConfirmPassword").value;
        if (password != confirmPassword) {
            alert("Passwords do not match.");
            return false;
        }
        return true;
    }
</script>

movie_ror/app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>